matrix:
  include:
    -  language: node_js
       sudo: required
       node_js:
         - 6
       services:
         - docker
       cache:
         directories:
           - node_modules
       env:
         global:
           - IMAGE_NAME=cloudchaos/fullstack-example-backend
           - version=0.0.2
           - MONGODB_HOST=mongodb
           - MONGODB_PORT=27017

       before_install:
         - cd backend
         - echo ${IMAGE_NAME}
         - docker run --name mongodb -d mongo
         - docker build --tag ${IMAGE_NAME} ./backend/
         - docker images

       install:
         - docker run --name movie-api --link ${MONGODB_HOST}:${MONGODB_PORT} -e "MONGODB_HOST=${MONGODB_HOST}" -e "MONGODB_PORT=${MONGODB_PORT}" -p 3000:3000 -d ${IMAGE_NAME}
         - docker ps
         - npm install

       before_deploy:
         - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
         - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
         - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"



    -  language: node_js
       sudo: required
       node_js:
         - 6
       services:
         - docker
       cache:
         directories:
           - node_modules
       env:
         global:
           - IMAGE_NAME=cloudchaos/fullstack-example-webui
           - version=0.0.2

       before_install:
         - cd frontend
         - docker build --tag ${IMAGE_NAME} ./webui/
         - docker images

       install:
         - docker run --name movie-webui -p 80:80 -d ${IMAGE_NAME}
         - docker ps
         - npm install

